### ISSUE TITLE
Process didn't exit successfully

### ISSUE THREAD

**Issue by Thubs** [p4ddy1/gbemulator#1]
On install I get the error "failed to run custom build command for alsa-sys v0.1.2"

for the full error

error: failed to run custom build command for `alsa-sys v0.1.2`

Caused by:
  process didn't exit successfully: `/home/thubs/gitshtuff/gbemulator-master/target/release/build/alsa-sys-1e546156c075211e/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=ALSA_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=ALSA_STATIC
  cargo:rerun-if-env-changed=ALSA_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"alsa\"` did not exit successfully: exit status: 1\nerror: could not find system library 'alsa' required by the 'alsa-sys' crate\n\n--- stderr\nPackage alsa was not found in the pkg-config search path.\nPerhaps you should add the directory containing `alsa.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'alsa' found\n"', /home/thubs/.cargo/registry/src/github.com-1ecc6299db9ec823/alsa-sys-0.1.2/build.rs:4:38
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by datp4ddy** [comment]
Hi. Which distribution are you using? Cpal needs the ALSA development files to build. Please check if the package containing them for your distribution is installed and try again

**Comment by Thubs** [comment]
Hey, I am using Pop!_OS 20.04 LTS, do you know where I can look to see if I have it installed and if not where to get it?

**Comment by datp4ddy** [comment]
I never used Pop!_OS but on Ubuntu the package is called alsa-lib

**Comment by Thubs** [comment]
I have verified that it has been installed and still nothing

**Comment by rwxroot** [comment]
@Thubs did you try to do a clean build?

**Comment by Thubs** [comment]
Yes I did

**Comment by rwxroot** [comment]
@Thubs I had this error while I was compiling but after I added `alsa-lib-devel`(I use fedora) it worked fine.

**Comment by datp4ddy** [comment]
@Thubs I think you also need the package libasound2-dev
